CREATE TABLE DEPARTMENT(
  DEPARTMENT_ID INT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE EMPLOYEE(
  EMPLOYEE_ID INT PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(100) NOT NULL,
  DEPARTMENT_ID INT NOT NULL,FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);
