SELECT EMPLOYEE_NAME FROM EMPLOYEE WHERE 
EMPLOYEE_ID=1;

SELECT EMPLOYEE_NAME FROM EMPLOYEE WHERE
EMPLOYEE_ID NOT IN (1,2);

SELECT DEPARTMENT_NAME FROM DEPARTMENT
WHERE DEPARTMENT_NAME LIKE "S%";

SELECT DEPARTMENT_NAME FROM DEPARTMENT
ORDER BY DEPARTMENT_ID DESC;
